name: Build (Windows)
jobs:
    Build:
        runs-on: windows-latest
        env:
            MSBUILD_PATH: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.exe
        steps:
            - name: Checkout Xolotl
              uses: actions/checkout@v4
              with:
                  path: xolotl
                  submodules: true
            - name: Checkout WXWidgets
              uses: actions/checkout@v4
              with:
                repository: wxwidgets/wxwidgets
                path: wxwidgets
                submodules: true
            - name: Build WX [64-bit]
              shell: cmd
              run: |
                "%MSBUILD_PATH%" "wx\build\msw\wx_vc17.sln" /Build "Release|x64"
            - name: Build WX [32-bit]
              shell: cmd
              run: |
                "%MSBUILD_PATH%" "wx\build\msw\wx_vc17.sln" /Build "Release|Win32"
            # - name: Build Xolotl
            #   shell: cmd
            #   run: |
            #     dir xolotl
            #     SET WX_BUILD_DIR=..\..\wx\build\msw
            #     "%MSBUILD_PATH%" ""
            #TODO FIGURE OUT HOW TO BUILD THIS SHIT ON WINDOWS
on: workflow_dispatch